### ISSUE TITLE
add gocd module

### ISSUE THREAD

**Issue by rasheedamir** [stakater/stakater#1]
add gocd module
- one gocd server
- multiple gocd agents

**Comment by rasheedamir** [comment]
tasks to do:
- open relevant ports
- ssh should be possible from bastion host only
- add dns entry so, that gocd is accessible on well known url!

**Comment by rasheedamir** [comment]
- where to put the gocd data? S3 bucket?
- restrict public access?
- backup the gocd pipelines in git repo as well

**Comment by rasheedamir** [comment]
- automatically save the gocd workspace in git repo; for easy retrieval

**Comment by rasheedamir** [comment]
- https://github.com/JorritSalverda/docker-gocd-agent

**Comment by rasheedamir** [comment]
added separate systemd services to run different CI & CD services - DONE

**Comment by rasheedamir** [comment]
task: create it alone with etcd and other components

**Comment by rasheedamir** [comment]
http://2mohitarora.blogspot.se/2014/05/manage-docker-containers-using-coreos_26.html

**Comment by rasheedamir** [comment]
https://github.com/xuwang/coreos-docker-dev/tree/master/apps/gocd

**Comment by rasheedamir** [comment]
@hazim1093 plz read this article:
http://2mohitarora.blogspot.se/2014/05/manage-docker-containers-using-coreos_26.html

also please add

gocd.<project-dns>
e.g.
gocd.stakater.com

**Comment by hazim1093** [comment]
Done
