### ISSUE TITLE
add build AMI workflow

### ISSUE THREAD

**Issue by rasheedamir** [stakater/stakater#11]
- add workflow that allows user to create an AMI given systemd units

register AMI
deregister (delete) AMI

**Comment by rasheedamir** [comment]
e.g.
- setup a base machine 
- use fleet to submit systemd unit
- now take snapshot
- register ami

?

**Comment by hazim1093** [comment]
Done in https://github.com/stakater/stakater/pull/21

Creation of instance(s) from the AMI in an auto scaling group is left as WIP for now due to the following issue: 
https://github.com/hashicorp/terraform/issues/7024
