### ISSUE TITLE
create global cluster which will host common stuff including gocd & docker registry

### ISSUE THREAD

**Issue by rasheedamir** [stakater/stakater#23]
create global admiral cluster which will host stuff that will be required oganization wide: e.g.
1. gocd
2. docker registry

**Comment by rasheedamir** [comment]
later on we will add maven repo etc.

**Comment by hazim1093** [comment]
We opted for separate GoCD and Docker Registry modules as docker registry does not need to be in an autoscaling group for now. 
Closing
