### ISSUE TITLE
define gocd pipeline with stages

### ISSUE THREAD

**Issue by rasheedamir** [stakater/stakater#29]
define gocd pipeline with following stages:
1. pull 
2. build
3. test
4. push
5. deploy to dev
6. build machine image
7. deploy to test/stage
8. deploy to prod?

some steps should be automatic on each commit and some should be manual

deployment of customer specific apps;
deployment of infrastructurs apps ( e.g. logstash, kibana, etc. )

these are just initial thoughts...

https://www.go.cd/2015/12/28/gocd-continuous-delivery-through-pipelines.html

**Comment by rasheedamir** [comment]
@hazim1093 check if we can take any help or inspiration from this: https://github.com/stakater/builder

**Comment by hazim1093** [comment]
Done, only step "deploy to dev" left in the gocd pipeline, which will be handled with https://github.com/stakater/stakater/issues/46
