### ISSUE TITLE
add docker registry

### ISSUE THREAD

**Issue by rasheedamir** [stakater/stakater#3]
add docker registery

https://github.com/coreos/unit-examples/tree/master/docker-registry-s3

**Comment by rasheedamir** [comment]
@hazim1093 also add dns entry for it i.e.

dockerrepo.<project-dns>
e.g.
dockerrepo.qbcheck.com

**Comment by hazim1093** [comment]
Done, added local dns entry like "registry.CLUSTER-NAME.local"
