### ISSUE TITLE
add retry on registry certificates upload

### ISSUE THREAD

**Issue by hazim1093** [stakater/stakater#35]
Registry Certificates are uploaded by the registry after it is created. 
The upload fails quite often due to reasons like "time out" or "unable to upload please try again" 

Add retry logic on uploading certificates so that certificate upload failure is minimized

**Comment by rasheedamir** [comment]
@hazim1093 you can take inspirations from here: 
https://github.com/xuwang/aws-terraform/commit/9d027ff3bd60ceee0fbf41c2cc5a4fe80f82b3c5
